title: Paint box
hero_image: images/banner.png
listed: true
copyedit: false
description: Make your own paint program
version: 4.1.0
last_tested: 2018-11-30
steps: 
- title: Introduction
- title: Make a pencil
- title: Coloured pencils
- title: 'Challenge: shortcuts'
  challenge: true
- title: Undo mistakes
- title: Change the pencil width
- title: 'Challenge: more pencils'
  challenge: true
- title: 'What next?'
