hero_image: images/banner.png
listed: true
copyedit: true
title: Balloons
description: Learn how to make a balloon-popping game!
version: 4
last_tested: 2018-04-02
steps: 
- title: Introduction
- title: Animating a balloon
- title: Random balloons
- title: 'Challenge: More randomness'
  challenge: true
- title: Popping balloons
- title: Adding a score
- title: Lots of balloons
- title: Adding a timer
- title: 'Challenge: More objects'
  challenge: true
- title: What next? 