title: Duplicate costumes in Scratch 3
hero_image: images/banner.png
description: generic-scratch3-duplicate-costumes description
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - title: Introduction

