hero_image: images/banner.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Moonhack Python 2017
description: Choose items to help someone stranded on the moon.
original_url: https://codeclubprojects.org/en-GB/python/moonhack-python
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Import the Starter Code
- title: Displaying a List
- title: 'Challenge: More Items'
- title: Interacting with the User
- title: 'Organizing the User Input '
- title: 'Evaluating the User Input '
- title: 'Will you make it to the Moon Base? '
- title: 'Challenge: Wrong Item'