title: Add a variable in Scratch
hero_image: images/banner.png
description: How to add a variable in Scratch
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Create a variable
