title: Create a high score
hero_image: images/banner.png
description: Learn how to create a high score for your Scratch game
theme: red # all possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Step one
