title: Adding a timer in Scratch
hero_image: images/banner.png
description: Adding a timer to your Scratch project
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: 
technologies: "scratch"
steps:
  - title: Adding a timer
